.git
.github
.vscode
.idea

**/.venv
**/__pycache__
**/.pytest_cache
**/.mypy_cache
**/.ruff_cache

**/*.py[cod]
**/.coverage
**/htmlcov
**/dist

**/*.log
**/*.tmp
**/*.temp

**/.env
**/.env.*

opssight/tests
opssight/src/opssight/generated

servicecore
sentinel-agent
docs
infra