spring.security.oauth2.resourceserver.jwt.issuer-uri=${NEXUSOPS_OIDC_ISSUER_URI:http://127.0.0.1:8081/realms/nexusops}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${NEXUSOPS_OIDC_JWK_SET_URI:http://127.0.0.1:8081/realms/nexusops/protocol/openid-connect/certs}

nexusops.security.client-id=${NEXUSOPS_OIDC_CLIENT_ID:servicecore}

servicecore.kafka.enabled=${SERVICECORE_KAFKA_ENABLED:true}
spring.kafka.bootstrap-servers=${SERVICECORE_KAFKA_BOOTSTRAP_SERVERS:kafka:19092}
