spring.application.name=servicecore

spring.profiles.default=dev

spring.datasource.url=jdbc:postgresql://${SERVICECORE_DB_HOST:localhost}:${SERVICECORE_DB_PORT:5433}/${SERVICECORE_DB_NAME:servicecore}
spring.datasource.username=${SERVICECORE_DB_USER:servicecore}
spring.datasource.password=${SERVICECORE_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.validate-migration-naming=true

management.endpoints.web.exposure.include=health,info