"""add monitoring constraints

Revision ID: c35a97784f93
Revises: 8080548180aa
Create Date: 2026-08-23 17:09:37.411990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c35a97784f93'
down_revision: Union[str, Sequence[str], None] = '8080548180aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_checks_host_id_name', 'checks', ['host_id', 'name'])
    op.create_check_constraint('ck_checks_interval_seconds_positive', 'checks', 'interval_seconds > 0')
    op.create_check_constraint('ck_checks_timeout_seconds_positive', 'checks', 'timeout_seconds > 0')
    op.create_unique_constraint('uq_hosts_name', 'hosts', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_hosts_name', 'hosts', type_='unique')
    op.drop_constraint('ck_checks_timeout_seconds_positive', 'checks', type_='check')
    op.drop_constraint('ck_checks_interval_seconds_positive', 'checks', type_='check')
    op.drop_constraint('uq_checks_host_id_name', 'checks', type_='unique')
    # ### end Alembic commands ###
