package com.nexusops.servicecore.audit.domain;

public enum AuditAction {
    KNOWLEDGE_ARTICLE_CREATED,
    KNOWLEDGE_ARTICLE_UPDATED,
    KNOWLEDGE_ARTICLE_PUBLISHED,
    KNOWLEDGE_ARTICLE_ARCHIVED,

    INCIDENT_CREATED,
    INCIDENT_UPDATED,
    INCIDENT_ASSIGNED,
    INCIDENT_STATUS_CHANGED,

    ASSET_CREATED,
    ASSET_ASSIGNED,
    ASSET_RETURNED,
    ASSET_STATUS_CHANGED
}